import streamlit as st
from google import genai

# 1. Page layout configuration
st.set_page_config(page_title="AI 5-Day Lesson Log Generator", layout="centered")

# Custom design to mimic the exact layout and look in the screenshot
st.markdown("""
    <style>
    .title-text { color: #1a73e8; font-weight: bold; text-align: center; font-size: 2.3rem; margin-bottom: 5px; }
    .subtitle-text { text-align: center; color: #3c4043; font-weight: 500; font-size: 1.1rem; margin-bottom: 15px; }
    .developer-text { text-align: center; color: #5f6368; font-size: 0.9rem; margin-bottom: 25px; }
    .developer-link { color: #1a73e8; text-decoration: none; font-weight: bold; }
    .intro-text { color: #5f6368; font-size: 0.95rem; line-height: 1.5; margin-bottom: 30px; }
    .custom-section-title { color: #b06000; font-weight: bold; font-size: 1.1rem; margin-top: 20px; margin-bottom: 15px; }
    .note-text { color: #5f6368; font-size: 0.85rem; font-style: italic; margin-top: 5px; }
    </style>
""", unsafe_allow_html=True)

# 2. Header and Introduction
st.markdown('<h1 class="title-text">AI 5-Day Lesson Log Generator</h1>', unsafe_allow_html=True)
st.markdown('<p class="subtitle-text">K-12 & SHS 5-Days Weekly Lesson Log</p>', unsafe_allow_html=True)
st.markdown('<p class="developer-text">Developed by: <a class="developer-link" href="#">Adonis T. Reyes</a></p>', unsafe_allow_html=True)

st.markdown('<p class="intro-text">Instantly create a detailed weekly lesson plan spanning 5 days. You can input your specific Standards/Competency, or leave them blank and let the AI generate them based on the Subject and Grade.</p>', unsafe_allow_html=True)

# 3. Basic Details Row (3 Columns)
col1, col2, col3 = st.columns([1, 1, 1.2])

with col1:
    subject = st.text_input("Subject", placeholder="e.g., Science, English, Math")
with col2:
    grade_level = st.text_input("Grade Level", placeholder="e.g., Grade 7, Kindergarten")
with col3:
    daily_topic = st.text_input("Weekly Topic/Theme (Optional: AI will suggest if empty)", placeholder="e.g., Fractions, Ecosystems")

st.markdown("---")

# 4. Custom Standards Section
st.markdown('<p class="custom-section-title">Custom Standards (A, B, C are Optional)</p>', unsafe_allow_html=True)

content_standard = st.text_area(
    "A. Content Standard", 
    placeholder="e.g., Demonstrates understanding of the four fundamental operations involving fractions."
)

performance_standard = st.text_area(
    "B. Performance Standard", 
    placeholder="e.g., Able to apply the four fundamental operations involving fractions to solve problems."
)

learning_competency = st.text_area(
    "C. Learning Competency (LC Code)", 
    placeholder="e.g., M6NS-Id-106: Adds and subtracts simple fractions and mixed numbers."
)

st.markdown('<p class="note-text"><b>D. Learning Objectives</b> will be automatically generated by the AI for each day based on the standards and competency provided above.</p>', unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

# 5. Generation Button and AI Prompt Logic
if st.button("Generate 5-Day Lesson Log", type="primary"):
    if not subject or not grade_level:
        st.error("Please fill in at least the 'Subject' and 'Grade Level' fields to get started.")
    else:
        try:
            api_key = st.secrets["GEMINI_API_KEY"]
            client = genai.Client(api_key=api_key)
            
            with st.spinner("Creating your 5-day weekly lesson log... This might take a moment longer."):
                # Upgraded prompt structure to force a 5-day layout mapping
                prompt = f"""
                You are an expert K-12 and Senior High School (SHS) curriculum developer specializing in DepEd educational guidelines.
                Create a complete, detailed 5-Day Weekly Lesson Log (spanning Day 1 to Day 5) based on these specifications:
                
                - Subject: {subject}
                - Grade Level: {grade_level}
                - Core Weekly Topic/Theme: {daily_topic if daily_topic else 'Automatically determine a comprehensive weekly theme appropriate for this level'}
                
                CRITICAL INSTRUCTIONS FOR STANDARDS:
                - Content Standard: {content_standard if content_standard else 'Develop a standard DepEd-aligned content standard.'}
                - Performance Standard: {performance_standard if performance_standard else 'Develop a standard DepEd-aligned performance standard.'}
                - Learning Competency / Code: {learning_competency if learning_competency else 'Provide appropriate learning competency codes.'}
                
                Please generate the output beautifully using Markdown headers. Keep the structure organized by dividing the workflow across 5 days (Day 1, Day 2, Day 3, Day 4, Day 5).
                
                For each day, explicitly detail:
                1. Daily Objective (Derived from the core standards)
                2. Subject Matter / Core Sub-topic for that specific day
                3. Learning Resources & Materials
                4. Procedures (Review/Motivation, Activity, Abstraction, Application, and Evaluation)
                
                Conclude the entire log with a single 'V. Remarks & Reflection' section at the very end.
                """
                
                response = client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=prompt,
                )
                
                st.success("5-Day Lesson Log Successfully Generated!")
                st.markdown("---")
                st.markdown(response.text)
                
        except Exception as e:
            st.error("Authentication Error: Please verify that your GEMINI_API_KEY is correctly added to your Streamlit App Secrets.")
