import streamlit as st
from google import genai

# 1. Page layout configuration
st.set_page_config(page_title="AI Daily Lesson Log Generator", layout="centered")

# Custom design to mimic the exact layout and look in the screenshot
st.markdown("""
    <style>
    .title-text { color: #1a73e8; font-weight: bold; text-align: center; font-size: 2.3rem; margin-bottom: 5px; }
    .subtitle-text { text-align: center; color: #3c4043; font-weight: 500; font-size: 1.1rem; margin-bottom: 15px; }
    .developer-text { text-align: center; color: #5f6368; font-size: 0.9rem; margin-bottom: 25px; }
    .developer-link { color: #1a73e8; text-decoration: none; font-weight: bold; }
    .intro-text { color: #5f6368; font-size: 0.95rem; line-height: 1.5; margin-bottom: 30px; }
    .custom-section-title { color: #b06000; font-weight: bold; font-size: 1.1rem; margin-top: 20px; margin-bottom: 15px; }
    .note-text { color: #5f6368; font-size: 0.85rem; font-style: italic; margin-top: 5px; }
    </style>
""", unsafe_allow_html=True)

# 2. Header and Introduction
st.markdown('<h1 class="title-text">AI Daily Lesson Log Generator</h1>', unsafe_allow_html=True)
st.markdown('<p class="subtitle-text">K-12 & SHS One Day Lesson Log</p>', unsafe_allow_html=True)
st.markdown('<p class="developer-text">Developed by:Adonis T. Reyes <a class="developer-link" href="#">Reymond P. Samoranos</a></p>', unsafe_allow_html=True)

st.markdown('<p class="intro-text">Instantly create a detailed single-day lesson plan. You can input your specific Standards/Competency, or leave them blank and let the AI generate them based on the Subject and Grade.</p>', unsafe_allow_html=True)

# 3. Basic Details Row (3 Columns)
col1, col2, col3 = st.columns([1, 1, 1.2])

with col1:
    subject = st.text_input("Subject", placeholder="e.g., Science, English, Math")
with col2:
    grade_level = st.text_input("Grade Level", placeholder="e.g., Grade 7, Kindergarten")
with col3:
    daily_topic = st.text_input("Daily Topic (Optional: AI will suggest if empty)", placeholder="e.g., World War II, Fractions, Ecosystems")

st.markdown("---")

# 4. Custom Standards Section
st.markdown('<p class="custom-section-title">Custom Standards (A, B, C are Optional)</p>', unsafe_allow_html=True)

content_standard = st.text_area(
    "A. Content Standard", 
    placeholder="e.g., Demonstrates understanding of the four fundamental operations involving fractions."
)

performance_standard = st.text_area(
    "B. Performance Standard", 
    placeholder="e.g., Able to apply the four fundamental operations involving fractions to solve problems."
)

learning_competency = st.text_area(
    "C. Learning Competency (LC Code)", 
    placeholder="e.g., M6NS-Id-106: Adds and subtracts simple fractions and mixed numbers."
)

st.markdown('<p class="note-text"><b>D. Learning Objectives</b> will be automatically generated by the AI based on the standards and competency provided above.</p>', unsafe_allow_html=True)

st.markdown("<br>", unsafe_allow_html=True)

# 5. Generation Button and AI Prompt Logic
if st.button("Generate 1-Day Lesson Log", type="primary"):
    if not subject or not grade_level:
        st.error("Please fill in at least the 'Subject' and 'Grade Level' fields to get started.")
    else:
        try:
            api_key = st.secrets["GEMINI_API_KEY"]
            client = genai.Client(api_key=api_key)
            
            with st.spinner("Generating your lesson log..."):
                # Building the smart, educational prompt structure
                prompt = f"""
                You are an expert K-12 and Senior High School (SHS) curriculum developer.
                Create a detailed, complete 1-Day Lesson Log based on these specifications:
                
                - Subject: {subject}
                - Grade Level: {grade_level}
                - Daily Topic: {daily_topic if daily_topic else 'Automatically determine a suitable topic for this grade and subject'}
                
                CRITICAL INSTRUCTIONS FOR STANDARDS:
                - Content Standard to guide the lesson: {content_standard if content_standard else 'Develop a standard DepEd-aligned content standard.'}
                - Performance Standard to guide the lesson: {performance_standard if performance_standard else 'Develop a standard DepEd-aligned performance standard.'}
                - Learning Competency / Code: {learning_competency if learning_competency else 'Provide appropriate learning competency codes.'}
                
                Please generate and format the output beautifully in Markdown using standard DepEd Daily Lesson Log (DLL) headers:
                I. OBJECTIVES (Derived from the standards, clearly stating Knowledge, Skills, and Attitudes)
                II. LEARNING CONTENT / TOPIC
                III. LEARNING RESOURCES (References, Materials)
                IV. PROCEDURES (Review/Motivation, Activity, Analysis, Abstraction, Application, Evaluation)
                V. REMARKS & REFLECTION
                """
                
                response = client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=prompt,
                )
                
                st.success("Lesson Log Successfully Generated!")
                st.markdown("---")
                st.markdown(response.text)
                
        except Exception as e:
            st.error("Authentication Error: Please verify that your GEMINI_API_KEY is correctly added to your Streamlit App Secrets.")
